### ISSUE TITLE
Suggestion: Add "Delete" option for limited amount of time after submitting

### ISSUE THREAD

**Issue by Moodkiller** [Fugiman/api.diff.pics#10]
Just had this issue now where I noticed that the column name didn't match the screenshot and afaik there is no way to delete a submission. Ideally, maybe for a time period of 5 minutes the submitter can delete a submission so that errors can be fixed (i.e screenshots that are 1 frame out or fix naming schemes)

**Comment by Fugiman** [comment]
There's now a "preview" button on the upload page that should help you find these issues before submitting.

That said, it doesn't really cost me anything to have "bad" comparisons, so feel free to just keep resubmitting them.
