### ISSUE TITLE
Bug: Mass Renaming name only applies to some screenshots

### ISSUE THREAD

**Issue by Moodkiller** [Fugiman/api.diff.pics#11]
I used the Mass Rename function on diff.pics / cevva2FgvXvt submission, and for whatever reason, screenshot #5, #6, #9 and #13 were the only ones to get the correct title name, the rest weren't so lucky.

**Comment by Fugiman** [comment]
This should finally be fixed... now that I rewrote the whole site. Unfortunately it's not retroactive. Thanks for the bug report!
