### ISSUE TITLE
ERROR JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by lsahnicne** [Fugiman/api.diff.pics#18]
So yeah, basically getting that line:
ERROR
JSON.parse: unexpected character at line 1 column 1 of the JSON data
when trying to submit images.
Waterfox 56.2.3

Also fonts looks off:
https://i.imgur.com/ahq4WoJ.png

**Comment by FugiTech** [comment]
Should be fixed now
